"""Event and alert management tools for FortiAnalyzer.

Based on FNDN FortiAnalyzer 7.6.4 Event Management API specifications.
Provides alert management, event handling, and SOC operations.
"""

import logging
from typing import Any

from fortianalyzer_mcp.api.client import FortiAnalyzerClient
from fortianalyzer_mcp.server import get_faz_client, mcp
from fortianalyzer_mcp.tool_annotations import CREATES, READ_ONLY, UPDATES
from fortianalyzer_mcp.utils.responses import redact
from fortianalyzer_mcp.utils.time_range import parse_time_range
from fortianalyzer_mcp.utils.validation import get_default_adom, validate_adom

logger = logging.getLogger(__name__)


def _get_client() -> FortiAnalyzerClient:
    """Get the FortiAnalyzer client instance."""
    client = get_faz_client()
    if not client:
        raise RuntimeError("FortiAnalyzer client not initialized")
    return client


async def _parse_time_range(time_range: str) -> dict[str, str]:
    """Parse time range using FAZ system TZ for alignment.

    Custom absolute ranges (``"start|end"``) skip the TZ lookup since
    the caller is already supplying explicit timestamps. Relative
    presets pull the cached FAZ timezone off the client so naive
    timestamps land in FAZ's local TZ.
    """
    if "|" in time_range:
        return parse_time_range(time_range)
    client = _get_client()
    faz_tz = await client.get_system_timezone()
    return parse_time_range(time_range, faz_tz=faz_tz)


@mcp.tool(annotations=READ_ONLY)
async def get_alerts(
    adom: str | None = None,
    time_range: str = "24-hour",
    filter: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> dict[str, Any]:
    """Get alert events from FortiAnalyzer.

    Retrieves security alerts generated by event handlers and correlation rules.

    Args:
        adom: ADOM name (default: from config DEFAULT_ADOM)
        time_range: Time range for alerts. Options:
            - "1-hour", "6-hour", "12-hour", "24-hour"
            - "1-day", "7-day", "30-day"
            - Custom: "2024-01-01 00:00:00|2024-01-02 00:00:00"
        filter: Filter expression (e.g., "severity==critical")
        limit: Maximum number of alerts to return (1-2000)
        offset: Record offset for pagination

    Returns:
        dict with alerts data and metadata

    Example:
        >>> result = await get_alerts(time_range="24-hour", limit=50)
        >>> print(f"Found {result.get('count', 0)} alerts")
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        # Enforce the documented 1-2000 range and non-negative offset.
        limit = max(1, min(limit, 2000))
        offset = max(0, offset)
        client = _get_client()
        tr = await _parse_time_range(time_range)

        logger.info(f"Getting alerts from ADOM {adom} for {time_range}")

        result = await client.get_alerts(
            adom=adom,
            time_range=tr,
            filter=filter,
            limit=limit,
            offset=offset,
        )

        data = result.get("data", []) if isinstance(result, dict) else result
        if not isinstance(data, list):
            data = [data] if data else []

        return {
            "status": "success",
            "adom": adom,
            "time_range": tr,
            "count": len(data),
            "data": data,
        }
    except Exception as e:
        logger.error(f"Failed to get alerts: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=READ_ONLY)
async def get_alert_count(
    adom: str | None = None,
    time_range: str = "24-hour",
    filter: str | None = None,
) -> dict[str, Any]:
    """Get count of alerts matching criteria.

    Args:
        adom: ADOM name (default: from config DEFAULT_ADOM)
        time_range: Time range for alerts
        filter: Filter expression

    Returns:
        dict with alert count
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()
        tr = await _parse_time_range(time_range)

        logger.info(f"Getting alert count from ADOM {adom}")

        result = await client.get_alerts_count(
            adom=adom,
            time_range=tr,
            filter=filter,
        )

        return {
            "status": "success",
            "adom": adom,
            "time_range": tr,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to get alert count: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=UPDATES)
async def acknowledge_alerts(
    alert_ids: list[str],
    user: str,
    adom: str | None = None,
) -> dict[str, Any]:
    """Acknowledge one or more alerts.

    Marks alerts as acknowledged for SOC workflow tracking.

    Args:
        alert_ids: List of alert IDs to acknowledge
        user: Username performing the acknowledgment
        adom: ADOM name (default: from config DEFAULT_ADOM)

    Returns:
        dict with acknowledgment result
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()

        logger.info(f"Acknowledging {len(alert_ids)} alerts in ADOM {adom} by {user}")

        result = await client.acknowledge_alerts(
            adom=adom,
            alert_ids=alert_ids,
            user=user,
        )

        return {
            "status": "success",
            "adom": adom,
            "acknowledged_count": len(alert_ids),
            "user": user,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to acknowledge alerts: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=UPDATES)
async def unacknowledge_alerts(
    alert_ids: list[str],
    user: str,
    adom: str | None = None,
) -> dict[str, Any]:
    """Unacknowledge one or more alerts.

    Removes acknowledgment status from alerts.

    Args:
        alert_ids: List of alert IDs to unacknowledge
        user: Username performing the operation
        adom: ADOM name (default: from config DEFAULT_ADOM)

    Returns:
        dict with result
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()

        logger.info(f"Unacknowledging {len(alert_ids)} alerts in ADOM {adom} by {user}")

        result = await client.unacknowledge_alerts(
            adom=adom,
            alert_ids=alert_ids,
            user=user,
        )

        return {
            "status": "success",
            "adom": adom,
            "unacknowledged_count": len(alert_ids),
            "user": user,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to unacknowledge alerts: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=READ_ONLY)
async def get_alert_logs(
    alert_ids: list[str],
    adom: str | None = None,
    limit: int = 1000,
    offset: int = 0,
) -> dict[str, Any]:
    """Get log entries associated with alerts.

    Retrieves the original log events that triggered the alerts.

    Args:
        alert_ids: List of alert IDs to get logs for
        adom: ADOM name (default: from config DEFAULT_ADOM)
        limit: Maximum number of logs (1-2000)
        offset: Record offset for pagination

    Returns:
        dict with alert logs
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        # Enforce the documented 1-2000 range and non-negative offset.
        limit = max(1, min(limit, 2000))
        offset = max(0, offset)
        client = _get_client()

        logger.info(f"Getting logs for {len(alert_ids)} alerts in ADOM {adom}")

        result = await client.get_alert_logs(
            adom=adom,
            alert_ids=alert_ids,
            limit=limit,
            offset=offset,
        )

        return {
            "status": "success",
            "adom": adom,
            "alert_count": len(alert_ids),
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to get alert logs: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=READ_ONLY)
async def get_alert_details(
    alert_ids: list[str],
    adom: str | None = None,
) -> dict[str, Any]:
    """Get extra details for alerts.

    Retrieves extended information about alerts including
    MITRE ATT&CK mappings and additional context.

    Args:
        alert_ids: List of alert IDs
        adom: ADOM name (default: from config DEFAULT_ADOM)

    Returns:
        dict with alert details
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()

        logger.info(f"Getting details for {len(alert_ids)} alerts in ADOM {adom}")

        result = await client.get_alert_extra_details(
            adom=adom,
            alert_ids=alert_ids,
        )

        return {
            "status": "success",
            "adom": adom,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to get alert details: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=CREATES)
async def add_alert_comment(
    alert_id: str,
    comment: str,
    user: str,
    adom: str | None = None,
) -> dict[str, Any]:
    """Add a comment to an alert.

    Adds analyst notes or comments for SOC workflow.

    Args:
        alert_id: Alert ID to comment on
        comment: Comment text
        user: Username adding the comment
        adom: ADOM name (default: from config DEFAULT_ADOM)

    Returns:
        dict with result
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()

        logger.info(f"Adding comment to alert {alert_id} in ADOM {adom}")

        result = await client.add_alert_comment(
            adom=adom,
            alert_id=alert_id,
            comment=comment,
            user=user,
        )

        return {
            "status": "success",
            "adom": adom,
            "alert_id": alert_id,
            "user": user,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to add alert comment: {e}")
        return {"status": "error", "message": redact(str(e))}


@mcp.tool(annotations=READ_ONLY)
async def get_alert_incident_stats(
    adom: str | None = None,
    time_range: str = "30-day",
    stat_type: str = "severity",
) -> dict[str, Any]:
    """Get alert and incident statistics.

    Retrieves aggregated statistics for SOC dashboards.

    Args:
        adom: ADOM name (default: from config DEFAULT_ADOM)
        time_range: Time range for statistics
        stat_type: Type of statistics:
            - "severity": Alert counts by severity
            - "severity-timescale": Severity over time
            - "status": Alert counts by status

    Returns:
        dict with statistics
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        client = _get_client()
        tr = await _parse_time_range(time_range)

        logger.info(f"Getting {stat_type} stats from ADOM {adom}")

        result = await client.get_alert_incident_stats(
            adom=adom,
            time_range=tr,
            stat_type=stat_type,
        )

        return {
            "status": "success",
            "adom": adom,
            "stat_type": stat_type,
            "time_range": tr,
            "data": result,
        }
    except Exception as e:
        logger.error(f"Failed to get alert-incident stats: {e}")
        return {"status": "error", "message": redact(str(e))}


_VALID_HANDLER_TYPES = {"basic", "correlation", "both"}


@mcp.tool(annotations=READ_ONLY)
async def get_alert_handlers(
    adom: str | None = None,
    handler_type: str = "both",
) -> dict[str, Any]:
    """Get event alert-handler (detection-rule) definitions.

    Reads the alert-handler configuration: each handler's name, id, and
    its rules (severity, filter, groupby, tags). This is the catalogue of
    detection rules the appliance runs — a read-only building block for
    the Wave-2 ``alert_rules`` skill.

    Args:
        adom: ADOM name (default: from config DEFAULT_ADOM)
        handler_type: Which handlers to return: "basic", "correlation" or
            "both" (default: "both")

    Returns:
        dict with handler definitions under "data" (keyed by "basic" and/or
        "correlation")

    Example:
        >>> result = await get_alert_handlers(handler_type="basic")
        >>> print(result["data"]["basic"])
    """
    try:
        adom = validate_adom(adom or get_default_adom())
        if handler_type not in _VALID_HANDLER_TYPES:
            valid = ", ".join(sorted(_VALID_HANDLER_TYPES))
            return {
                "status": "error",
                "message": f"Validation error: Invalid handler_type '{handler_type}'. "
                f"Must be one of: {valid}",
            }
        client = _get_client()

        logger.info(f"Getting {handler_type} alert handlers from ADOM {adom}")

        result = await client.get_alert_handlers(adom=adom, handler_type=handler_type)
        return {"status": "success", "adom": adom, "handler_type": handler_type, "data": result}
    except Exception as e:
        logger.error(f"Failed to get alert handlers: {e}")
        return {"status": "error", "message": redact(str(e))}
